services:
  - type: web
    name: ddos-defender-backend
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:app
    env: python
    python:
      version: 3.9.12
